export const GET_DIALOGS = 'GET_DIALOGS';
export const SEARCH_IN_LIST_DIALOGS = 'SEARCH_IN_LIST_DIALOGS';
export const SET_ACTIVE_DIALOG = 'SET_ACTIVE_DIALOG';
export const ADD_DIALOG = "ADD_DIALOG";
export const REMOVE_DIALOG = "REMOVE_DIALOG";
